### ISSUE TITLE
The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'

### ISSUE THREAD

**Issue by cafeed28** [BlackTeaML/Android-ML#2]
```
set NDK=/android-ndk-r23
cmake ./build -DCMAKE_ANDROID_NDK=%NDK%
```

output
[CMakeError.log](https://github.com/BlackTeaML/Android-ML/files/7345702/CMakeError.log)
[CMakeOutput.log](https://github.com/BlackTeaML/Android-ML/files/7345704/CMakeOutput.log)

**Comment by Partur-dev** [comment]
Fixed in https://github.com/BlackTeaML/Android-ML/commit/a74b5bb624c198f923d76f6c1e1cd79125d26ea3
