### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by viralium** [BlackTeaML/Android-ML#5]
![image](https://github.com/BlackTeaML/Android-ML/assets/129858326/3459c4ea-76e3-4cf8-a4f3-3e5778364085)
I added headers for FLAlertLayer, ButtonSprite

**Comment by iAndyHD3** [comment]
use [gd.h for android](https://github.com/ItalianApkDownloader/gdh)

**Comment by viralium** [comment]
![image](https://github.com/BlackTeaML/Android-ML/assets/129858326/bbc5820f-f7ff-4571-b8de-97fe1fe303aa)
Non fixed

**Comment by iAndyHD3** [comment]
oh, you are using new c++ which is not supported. you can use [my example mod](https://github.com/iAndyHD3/gd-mod-example-android)

**Comment by viralium** [comment]
i use old c++

**Comment by iAndyHD3** [comment]
you need to use ndk 16b

**Comment by viralium** [comment]
i use
